import work.ASGinzburgDraft.GradedOrdinaryRingDualGradeFinite
import work.ASGinzburgDraft.GradedOrdinaryRingDualInternalGrading

/-! The actual top ordinary Hom quotient is generated by its surviving
homogeneous degree when the other genuine homogeneous degrees are boundaries. -/
namespace ASGinzburg
open CategoryTheory
open scoped ModuleCat.Algebra
universe u v
variable {k : Type u} [Field k] {R : Type v} [Ring R] [Algebra k R]

noncomputable def ordinaryRingDualMapField {P Q : ModuleCat.{v} R} (a : P ⟶ Q) :
    ordinaryRingDual R Q →ₗ[k] ordinaryRingDual R P where
  toFun := ordinaryRingDualMap R a
  map_add' := (ordinaryRingDualMap R a).map_add
  map_smul' c f := by
    apply LinearMap.ext
    intro x
    change (c • f) (a x) = c • (f (a x))
    exact ordinaryRingDual_field_smul_apply Q c f (a x)

namespace GradedOrdinaryModuleData
variable {G : ℤ → Submodule k R} [DirectSum.Decomposition G]
variable (M L : GradedOrdinaryModuleData k R G)
variable (hG : ∀ p q : ℤ, ∀ a ∈ G p, ∀ b ∈ G q, a * b ∈ G (p + q))

include hG in
 theorem ringDualTopQuotient_degree_surjective [Module.Finite R M.ringModule]
    (a : M.ringModule ⟶ L.ringModule) (q₀ : ℤ)
    (hExact : ∀ q : ℤ, q ≠ q₀ → ∀ f ∈ M.ringDualGrade q,
      ∃ g : ordinaryRingDual R L.ringModule, ordinaryRingDualMap R a g = f) :
    Function.Surjective (((LinearMap.range (ordinaryRingDualMapField (k := k) a)).mkQ).comp
      (M.ringDualGrade q₀).subtype) := by
  classical
  let B := LinearMap.range (ordinaryRingDualMapField (k := k) a)
  intro z
  obtain ⟨f,rfl⟩ := B.mkQ_surjective z
  obtain ⟨s,hs⟩ := M.ringDualComponent_finiteSupport hG f
  have hkill (q : ℤ) (hq : q ≠ q₀) : B.mkQ (M.ringDualComponent hG f q) = 0 := by
    obtain ⟨g,hg⟩ := hExact q hq _ (M.ringDualComponent_mem hG f q)
    exact (Submodule.Quotient.mk_eq_zero B).mpr ⟨g,hg⟩
  have he : B.mkQ f = B.mkQ (M.ringDualComponent hG f q₀) := by
    calc
      B.mkQ f = B.mkQ (∑ q ∈ s, M.ringDualComponent hG f q) :=
        congrArg B.mkQ (M.ringDual_sum_components hG f s hs).symm
      _ = ∑ q ∈ s, B.mkQ (M.ringDualComponent hG f q) := map_sum _ _ _
      _ = B.mkQ (M.ringDualComponent hG f q₀) := by
        apply Finset.sum_eq_single q₀
        · intro q _ hq
          exact hkill q hq
        · intro hq
          rw [hs q₀ hq, map_zero]
  refine ⟨⟨M.ringDualComponent hG f q₀, M.ringDualComponent_mem hG f q₀⟩, ?_⟩
  exact he.symm

include hG in
 theorem ringDualTopQuotient_finite [Module.Finite R M.ringModule]
    [∀ q : ℤ, Module.Finite k (G q)] (a : M.ringModule ⟶ L.ringModule) (q₀ : ℤ)
    (hExact : ∀ q : ℤ, q ≠ q₀ → ∀ f ∈ M.ringDualGrade q,
      ∃ g : ordinaryRingDual R L.ringModule, ordinaryRingDualMap R a g = f) :
    Module.Finite k (ordinaryRingDual R M.ringModule ⧸
      LinearMap.range (ordinaryRingDualMapField (k := k) a)) := by
  letI := M.ringDualGrade_finite q₀
  exact Module.Finite.of_surjective
    (((LinearMap.range (ordinaryRingDualMapField (k := k) a)).mkQ).comp
      (M.ringDualGrade q₀).subtype)
    (M.ringDualTopQuotient_degree_surjective L hG a q₀ hExact)

end GradedOrdinaryModuleData
end ASGinzburg
