import ASGinzburg.RegularCoproductActions
import ASGinzburg.TotalModuleSpaces
import ASGinzburg.ASDualityRegularCoproduct
import ASGinzburg.ASResolutionExtColimits
import ASGinzburg.RightModuleHomKernel
import ASGinzburg.HomologicalColimitClosure
import ASGinzburg.RightModuleExtNaturalSequence
import ASGinzburg.FiniteCoproductHomColimits
import ASGinzburg.LeftModuleADual
import ASGinzburg.LeftModuleExt
import ASGinzburg.RepresentableHomColimits
import ASGinzburg.ASDualityLeftComponents
import ASGinzburg.SimpleLeftModules
import ASGinzburg.LeftModules
import ASGinzburg.RightModuleExtLeftAction
import ASGinzburg.ASDualityEquivalence
import ASGinzburg.RightModuleHomFinite
import ASGinzburg.ASResolutionExtFinite
import ASGinzburg.ASResolutionExtBounds
import ASGinzburg.CutQuiver
import ASGinzburg.CutPotential
import ASGinzburg.CyclicDerivative
import ASGinzburg.PathAlgebra
import ASGinzburg.ZAlgebra
import ASGinzburg.Representables
import ASGinzburg.RightModuleAbelian
import ASGinzburg.RightModuleHomology
import ASGinzburg.RightModuleProjectives
import ASGinzburg.RightModuleEnoughProjectives
import ASGinzburg.RightSubmodules
import ASGinzburg.SimpleRightModules
import ASGinzburg.RightModuleRadical
import ASGinzburg.RightModuleMinimality
import ASGinzburg.RightModuleSimpleHom
import ASGinzburg.ASResolution
import ASGinzburg.RightModuleExtLinear
import ASGinzburg.ASResolutionComplex
import ASGinzburg.ASRegular
import ASGinzburg.ASResolutionHomComplex
import ASGinzburg.ASDualityHomTerms
import ASGinzburg.RightModuleExtSequence
import ASGinzburg.ASDualityHomCohomology
import ASGinzburg.ASResolutionSyzygies
import ASGinzburg.ASDualityExt
import ASGinzburg.ASDualityDimension
import ASGinzburg.RightModuleExt
import ASGinzburg.ExtDimension
import ASGinzburg.TopCohomology
import ASGinzburg.WindowPeriodicity
import ASGinzburg.Conjugation
import ASGinzburg.Hilbert
import ASGinzburg.Tensor333
import ASGinzburg.Triangle333
import ASGinzburg.GinzburgGrading

/-!
# AS--Ginzburg formalization checkpoint

All imports contain checked definitions and proofs. This checkpoint does
not yet contain a formal statement or proof of Theorem 3.2 or Corollary
5.2. See STATUS.md and GAPS.md for the exact scope and unresolved bridges.
-/
