import ASGinzburg.TotalModuleLocalUnits
import ASGinzburg.TotalAlgebraEmbedding
import ASGinzburg.TotalAlgebra
import ASGinzburg.TotalAlgebraLocalUnits
import ASGinzburg.TotalComponentActions
import ASGinzburg.TotalAlgebraLift
import ASGinzburg.TotalModuleRepresentations
import ASGinzburg.LocallyUnitalModules
import ASGinzburg.TotalModuleFunctors
import ASGinzburg.TotalModuleFullness
import ASGinzburg.UnitizationComponentActions
import ASGinzburg.UnitizationComponentModules
import ASGinzburg.UnitizationComponentFunctors
import ASGinzburg.UnitizationComponentSums
import ASGinzburg.LocallyUnitalEquivalence
import ASGinzburg.LocallyUnitalAbelian
import ASGinzburg.ExactEquivalenceExt
import ASGinzburg.LocallyUnitalExtComparison
import ASGinzburg.LocallyUnitalExtNaturality
import ASGinzburg.RegularTotalAlgebra
import ASGinzburg.RegularRightModule
import ASGinzburg.LinearExtTransport
import ASGinzburg.RegularLeftMultiplication
import ASGinzburg.RegularExtComparison
import ASGinzburg.RegularExtLeftModule
import ASGinzburg.RegularCoproductActions
import ASGinzburg.TotalModuleSpaces
import ASGinzburg.ASDualityRegularCoproduct
import ASGinzburg.ASResolutionExtColimits
import ASGinzburg.RightModuleHomKernel
import ASGinzburg.HomologicalColimitClosure
import ASGinzburg.RightModuleExtNaturalSequence
import ASGinzburg.FiniteCoproductHomColimits
import ASGinzburg.LeftModuleADual
import ASGinzburg.LeftModuleExt
import ASGinzburg.RepresentableHomColimits
import ASGinzburg.ASDualityLeftComponents
import ASGinzburg.SimpleLeftModules
import ASGinzburg.LeftModules
import ASGinzburg.RightModuleExtLeftAction
import ASGinzburg.ASDualityEquivalence
import ASGinzburg.RightModuleHomFinite
import ASGinzburg.ASResolutionExtFinite
import ASGinzburg.ASResolutionExtBounds
import ASGinzburg.CutQuiver
import ASGinzburg.CutPotential
import ASGinzburg.CyclicDerivative
import ASGinzburg.PathAlgebra
import ASGinzburg.ZAlgebra
import ASGinzburg.Representables
import ASGinzburg.RightModuleAbelian
import ASGinzburg.RightModuleHomology
import ASGinzburg.RightModuleProjectives
import ASGinzburg.RightModuleEnoughProjectives
import ASGinzburg.RightSubmodules
import ASGinzburg.SimpleRightModules
import ASGinzburg.RightModuleRadical
import ASGinzburg.RightModuleMinimality
import ASGinzburg.RightModuleSimpleHom
import ASGinzburg.ASResolution
import ASGinzburg.RightModuleExtLinear
import ASGinzburg.ASResolutionComplex
import ASGinzburg.ASRegular
import ASGinzburg.ASResolutionHomComplex
import ASGinzburg.ASDualityHomTerms
import ASGinzburg.RightModuleExtSequence
import ASGinzburg.ASDualityHomCohomology
import ASGinzburg.ASResolutionSyzygies
import ASGinzburg.ASDualityExt
import ASGinzburg.ASDualityDimension
import ASGinzburg.RightModuleExt
import ASGinzburg.ExtDimension
import ASGinzburg.TopCohomology
import ASGinzburg.WindowPeriodicity
import ASGinzburg.Conjugation
import ASGinzburg.Hilbert
import ASGinzburg.Tensor333
import ASGinzburg.Triangle333
import ASGinzburg.GinzburgGrading
import ASGinzburg.ModuleBidualEvaluation
import ASGinzburg.FiniteProjectiveBidual
import ASGinzburg.FiniteProjectiveDuality
import ASGinzburg.FiniteProjectiveComplexDuality

import ASGinzburg.ComplexDegreeReverse
import ASGinzburg.HomotopyDegreeReverse
import ASGinzburg.BoundedCochainDuality

import ASGinzburg.FiniteProjectiveClosure
import ASGinzburg.ASFiniteProjectiveComplex

import ASGinzburg.ASDualityComplexExactness
import ASGinzburg.RightModuleExtLeftSequence
import ASGinzburg.ASDualityTopCokernel
import ASGinzburg.ASLeftResolution

import ASGinzburg.ProjectiveResolutionSyzygies
import ASGinzburg.ProjectiveResolutionHomComplex
import ASGinzburg.ASLeftBidualComplex
import ASGinzburg.ASLeftExtConcentration

import ASGinzburg.LeftModuleExtSequence
import ASGinzburg.LeftModuleExtNaturalSequence
import ASGinzburg.LeftModuleExtRightSequence
import ASGinzburg.ASLeftExtReciprocity
import ASGinzburg.FiniteDimensionalModules
import ASGinzburg.FiniteVertexFiltration
import ASGinzburg.FiniteDimensionalExtConcentration
import ASGinzburg.ExtComponentContravariance
import ASGinzburg.ExtComponentShortExact
import ASGinzburg.FiniteDimensionalExtDuality
import ASGinzburg.FiniteDimensionalProjectiveDimension
import ASGinzburg.FiniteProjectivePresentations
import ASGinzburg.FiniteProjectiveExtensionClosure
import ASGinzburg.ShortExactKernels
import ASGinzburg.ProjectiveExtensionCovers
import ASGinzburg.FiniteProjectiveResolutionLength
import ASGinzburg.ASFiniteDimensionalResolutionLength
import ASGinzburg.FourTermProjectiveResolution
import ASGinzburg.FiniteProjectiveFourTermResolution
import ASGinzburg.ASFiniteDimensionalProjectiveResolution
import ASGinzburg.ProjectiveResolutionHomExactness
import ASGinzburg.FiniteProjectiveHomColimits
import ASGinzburg.FiniteProjectiveResolutionExtColimits

import ASGinzburg.RightResolutionDuality
import ASGinzburg.LeftResolutionDuality
import ASGinzburg.RightResolutionExtBidual
import ASGinzburg.LeftResolutionExtBidual
import ASGinzburg.FiniteDimensionalExtBidual
import ASGinzburg.FiniteDimensionalRegularExtComparison

import ASGinzburg.ExtClassNaturality
import ASGinzburg.ProjectiveResolutionSyzygyNaturality
import ASGinzburg.ResolutionExtBoundaryNaturality
import ASGinzburg.DualResolutionComparisonMaps
import ASGinzburg.ResolutionExtBidualNaturality
import ASGinzburg.FiniteDimensionalExtEquivalence

import ASGinzburg.FiniteDiagramClosureMaps
import ASGinzburg.FiniteDimensionalAbelian
import ASGinzburg.SmallVectorDuality
import ASGinzburg.ModuleVectorDuality
import ASGinzburg.FiniteDimensionalVectorDuality
import ASGinzburg.FiniteDimensionalNakayama

import ASGinzburg.RightSingleSupportIsomorphism
import ASGinzburg.SimpleVectorDuality
import ASGinzburg.FiniteDimensionalSimpleTranslation
import ASGinzburg.FiniteDimensionalWindows
import ASGinzburg.FiniteDimensionalWindowSequences
import ASGinzburg.NakayamaWindowSupport

import ASGinzburg.NormalizedProjectiveCovers
import ASGinzburg.NakayamaInverseWindowSupport
import ASGinzburg.NakayamaWindowEquivalence
import ASGinzburg.TruncatedRepresentables
import ASGinzburg.FiniteWindowProjectives
import ASGinzburg.NakayamaWindowProjectives

import ASGinzburg.TruncatedRepresentableHom
import ASGinzburg.TruncatedRepresentableRestrictions
import ASGinzburg.TruncatedCoverComponents

import ASGinzburg.DirectSumDuality
import ASGinzburg.TotalVectorDuality
import ASGinzburg.TotalVectorDualActions
import ASGinzburg.NakayamaWindowComparisons
import ASGinzburg.NakayamaUnderlyingMaps
import ASGinzburg.NakayamaRepresentableUnderlying

import ASGinzburg.NakayamaWindowNormalization
import ASGinzburg.NakayamaWindowComponents
import ASGinzburg.NakayamaWindowCoherence
import ASGinzburg.PeriodInverse
import ASGinzburg.ASPeriodicity

import ASGinzburg.LeftHomColimits
import ASGinzburg.LeftFiniteExtColimits
import ASGinzburg.LeftRegularCoproduct
import ASGinzburg.LeftFiniteRegularExtComparison
import ASGinzburg.LeftRegularTotalAlgebra
import ASGinzburg.RegularLeftModule
import ASGinzburg.LeftRegularExtComparison
import ASGinzburg.RegularRightMultiplication
import ASGinzburg.LeftFiniteTotalExt

import ASGinzburg.ASGenerators
import ASGinzburg.ASPathPresentation
import ASGinzburg.ASMinimalGenerators
import ASGinzburg.ASIndecomposables
import ASGinzburg.UnrolledPathAlgebra
import ASGinzburg.CoproductRadicals
import ASGinzburg.CoproductRadicalQuotients
import ASGinzburg.UnrolledPathFiniteness
import ASGinzburg.UnrolledPathZAlgebra
import ASGinzburg.ASGeneratorDimensions
import ASGinzburg.UnrolledPathPresentationMorphism
import ASGinzburg.ASGeneratorBasis
import ASGinzburg.UnrolledPathIndecomposables
import ASGinzburg.ZAlgebraHomomorphisms
import ASGinzburg.UnrolledSingleArrows

import ASGinzburg.UnrolledPathArrowClasses
import ASGinzburg.FreeLinearKernelSupport
import ASGinzburg.UnrolledPathKernelSquare
import ASGinzburg.LinearIdealProducts
import ASGinzburg.UnrolledPathFiltration
import ASGinzburg.UnrolledPathIdeals
import ASGinzburg.ASPresentationKernel
import ASGinzburg.QuotientZAlgebra
import ASGinzburg.ZAlgebraIsomorphisms
import ASGinzburg.ASPresentationQuotient

import ASGinzburg.ClosedPathPotentials
import ASGinzburg.PathWordEmbeddings
import ASGinzburg.PathCyclicDerivativeSupport
import ASGinzburg.PathCyclicDerivatives
import ASGinzburg.CyclicDerivativeDegrees
import ASGinzburg.PathCyclicDerivativeDegrees
import ASGinzburg.CyclicDerivativeCommutators
import ASGinzburg.PathUnrolling
import ASGinzburg.PathDegreeUnrolling
import ASGinzburg.GeneratedLinearIdeals
import ASGinzburg.UnrolledJacobianRelations
import ASGinzburg.UnrolledComponentHeights
import ASGinzburg.TrianglePeriodicity
import ASGinzburg.UnrolledJacobianAlgebra

import ASGinzburg.GinzburgPaths
import ASGinzburg.GinzburgPathAlgebra
import ASGinzburg.GinzburgPathWords
import ASGinzburg.GinzburgDegreeZeroAlgebra
import ASGinzburg.GinzburgGeneratorDifferentials
import ASGinzburg.GinzburgGeneratorGradings
import ASGinzburg.GinzburgPathDifferential
import ASGinzburg.GinzburgSupportedProducts
import ASGinzburg.GinzburgDifferentialGradings
import ASGinzburg.GinzburgLeibniz
import ASGinzburg.GinzburgDifferentialSign
import ASGinzburg.GinzburgDegreeZeroDifferential

import ASGinzburg.GinzburgSquareProducts

import ASGinzburg.VertexCyclicCommutators
import ASGinzburg.PathCyclicCommutators
import ASGinzburg.GinzburgLoopSquare
import ASGinzburg.GinzburgSquareZero
import ASGinzburg.GinzburgCochainComplex
import ASGinzburg.GinzburgRegularity
import ASGinzburg.PathLinearIdeals
import ASGinzburg.GinzburgDegreeNegOnePaths
import ASGinzburg.GinzburgBoundarySpaces
import ASGinzburg.GinzburgBoundaryProducts
import ASGinzburg.PathJacobianIdeal
import ASGinzburg.GinzburgDualContexts
import ASGinzburg.GinzburgJacobianBoundaries
import ASGinzburg.GinzburgHomologyZero
import ASGinzburg.GinzburgTotalHomologyZero
import ASGinzburg.GinzburgPositiveHomology

import ASGinzburg.GinzburgPathFiniteness
import ASGinzburg.GinzburgCutCochainComplex
import ASGinzburg.GinzburgCutProjections
import ASGinzburg.GinzburgCutRetracts
import ASGinzburg.GinzburgCutBounds
import ASGinzburg.PathCutGrading
import ASGinzburg.PathJacobianGrading
import ASGinzburg.GinzburgCutDegreeZero
import ASGinzburg.GinzburgCutHomologyFinite
import ASGinzburg.GinzburgCutHomologyZero
import ASGinzburg.UnrolledPathWords
import ASGinzburg.PathCutUnrollingEquiv
import ASGinzburg.GinzburgCycleBoundary
import ASGinzburg.GinzburgCutDecomposition
import ASGinzburg.GinzburgCutRegularity

import ASGinzburg.UnrolledPathErasure
import ASGinzburg.UnrolledJacobianErasure
import ASGinzburg.PathCutUnrollingComparison
import ASGinzburg.UnrolledErasureIdeals
import ASGinzburg.UnrolledJacobianIdealErasure
import ASGinzburg.PathJacobianContexts
import ASGinzburg.PathCutProducts
import ASGinzburg.PathJacobianHomogeneousContexts
import ASGinzburg.PathQuotientProducts
import ASGinzburg.PathBetweenSheets
import ASGinzburg.BetweenSheetLinearEquiv
import ASGinzburg.UnrolledJacobianLiftIdeal
import ASGinzburg.UnrolledJacobianContexts
import ASGinzburg.BetweenSheetJacobianIdeals
import ASGinzburg.JacobianUnrollingQuotient
import ASGinzburg.JacobianCutQuotientProducts
import ASGinzburg.JacobianUnrollingProducts

import ASGinzburg.GinzburgZeroProducts
import ASGinzburg.GinzburgZeroQuotientProducts
import ASGinzburg.GinzburgHomologyZeroProducts
import ASGinzburg.GinzburgJacobianProducts
import ASGinzburg.GinzburgCutZeroProducts
import ASGinzburg.GinzburgCutZeroQuotientProducts
import ASGinzburg.GinzburgCutHomologyZeroProducts
import ASGinzburg.GinzburgCutJacobianProducts
import ASGinzburg.GinzburgCutHomologyUnits
import ASGinzburg.GinzburgHomologyZAlgebra
import ASGinzburg.FiniteComponentAlgebra
import ASGinzburg.PathJacobianRing
import ASGinzburg.FiniteComponentAlgebraEquiv
import ASGinzburg.GinzburgHomologyUnits
import ASGinzburg.GinzburgHomologyRing
import ASGinzburg.PathJacobianRingQuotient

import ASGinzburg.HomologyAugmentation
import ASGinzburg.GinzburgAugmentation
import ASGinzburg.GinzburgCutAugmentation
import ASGinzburg.GinzburgUnrolledAugmentation
import ASGinzburg.GinzburgLastGenerator
import ASGinzburg.GinzburgAugmentationBasis
import ASGinzburg.GinzburgAugmentationIdeal
import ASGinzburg.GinzburgLastGeneratorGradings
import ASGinzburg.GinzburgAugmentationGradedFree
import ASGinzburg.GinzburgAugmentationComplex
import ASGinzburg.GinzburgAugmentationHomology
import ASGinzburg.GinzburgAugmentationRegularity

/-!
# AS--Ginzburg formalization checkpoint

All imports contain checked definitions and proofs. This checkpoint does
not yet contain a formal statement or proof of Theorem 3.2 or Corollary
5.2. See STATUS.md and GAPS.md for the exact scope and unresolved bridges.
-/

