import ASGinzburg

#print axioms ASGinzburg.ZAlgebra.ASResolution.homComplex_isZero_ge_four
#print axioms ASGinzburg.ZAlgebra.ASResolution.homComplex_tau_representable_low_terms_isZero
#print axioms ASGinzburg.ZAlgebra.ASResolution.homComplex_tau_representable_top_homologyLinearEquiv
#print axioms ASGinzburg.ZAlgebra.ASResolution.homComplex_tau_representable_low_homology_isZero
#print axioms ASGinzburg.ZAlgebra.ASResolution.homComplex_tau_representable_high_homology_isZero
#print axioms ASGinzburg.ZAlgebra.ASResolution.homComplex_tau_representable_top_homology_finrank
#print axioms ASGinzburg.CutQuiver.tau_incomingSource_height_gt
#print axioms ASGinzburg.ZAlgebra.asDualityHomTerm₀_zero
#print axioms ASGinzburg.ZAlgebra.asDualityHomTerm₁_zero
#print axioms ASGinzburg.ZAlgebra.asDualityHomTerm₂_zero
#print axioms ASGinzburg.ZAlgebra.asDualityHomTerm₃Equiv
#print axioms ASGinzburg.ZAlgebra.asExtTotalRank
#print axioms ASGinzburg.ZAlgebra.ASRegular
#print axioms ASGinzburg.ZAlgebra.ASRegular.resolution
#print axioms ASGinzburg.ZAlgebra.ASRegular.projectiveResolution
#print axioms ASGinzburg.ZAlgebra.ASRegular.projectiveResolution_isZero_ge_four
#print axioms ASGinzburg.ZAlgebra.asExtRank_le_total
#print axioms ASGinzburg.ZAlgebra.ASRegular.extRank_le_one
#print axioms ASGinzburg.ZAlgebra.ASRegular.extFinite
#print axioms ASGinzburg.ZAlgebra.ASRegular.extFinrank_le_one
#print axioms ASGinzburg.ZAlgebra.asExtRank_zero_iff
#print axioms ASGinzburg.CutQuiver.incomingArrows
#print axioms ASGinzburg.CutQuiver.outgoingArrows
#print axioms ASGinzburg.CutQuiver.incomingArrowsFintype
#print axioms ASGinzburg.CutQuiver.outgoingArrowsFintype
#print axioms ASGinzburg.CutQuiver.incomingSource
#print axioms ASGinzburg.CutQuiver.outgoingTarget
#print axioms ASGinzburg.CutQuiver.incoming_liftedTarget
#print axioms ASGinzburg.CutQuiver.outgoing_liftedSource
#print axioms ASGinzburg.CutQuiver.incomingSource_height_lt
#print axioms ASGinzburg.CutQuiver.outgoingTarget_height_gt
#print axioms ASGinzburg.ZAlgebra.rightModule_coproduct_projective
#print axioms ASGinzburg.ZAlgebra.asResolutionTerm₁
#print axioms ASGinzburg.ZAlgebra.asResolutionTerm₂
#print axioms ASGinzburg.ZAlgebra.asResolutionTerm₁Projective
#print axioms ASGinzburg.ZAlgebra.asResolutionTerm₂Projective
#print axioms ASGinzburg.ZAlgebra.ASResolution
#print axioms ASGinzburg.ZAlgebra.ASResolution.hom_d₁_simple_zero
#print axioms ASGinzburg.ZAlgebra.ASResolution.hom_d₂_simple_zero
#print axioms ASGinzburg.ZAlgebra.ASResolution.hom_d₃_simple_zero
#print axioms ASGinzburg.ZAlgebra.ASResolution.complexTerm
#print axioms ASGinzburg.ZAlgebra.ASResolution.complexDifferential
#print axioms ASGinzburg.ZAlgebra.ASResolution.complexDifferential_sq
#print axioms ASGinzburg.ZAlgebra.ASResolution.complex
#print axioms ASGinzburg.ZAlgebra.ASResolution.complexTermProjective
#print axioms ASGinzburg.ZAlgebra.ASResolution.complex_exactAt_succ
#print axioms ASGinzburg.ZAlgebra.ASResolution.augmentation
#print axioms ASGinzburg.ZAlgebra.ASResolution.augmentationQuasiIso
#print axioms ASGinzburg.ZAlgebra.ASResolution.toProjectiveResolution
#print axioms ASGinzburg.ZAlgebra.ASResolution.complex_isZero_ge_four
#print axioms ASGinzburg.ZAlgebra.ASResolution.homDifferential
#print axioms ASGinzburg.ZAlgebra.ASResolution.homDifferential_sq
#print axioms ASGinzburg.ZAlgebra.ASResolution.homComplex
#print axioms ASGinzburg.ZAlgebra.ASResolution.complexDifferential_minimal
#print axioms ASGinzburg.ZAlgebra.ASResolution.homDifferential_simple_zero
#print axioms ASGinzburg.ZAlgebra.ASResolution.homComplex_simple_d_zero
#print axioms ASGinzburg.ZAlgebra.ASResolution.homComplex_simple_d_all_zero
#print axioms ASGinzburg.ZAlgebra.ASResolution.homComplex_simple_homologyIso
#print axioms ASGinzburg.conjugateHom
#print axioms ASGinzburg.conjugateHom_apply
#print axioms ASGinzburg.conjugateHom_id
#print axioms ASGinzburg.conjugateHom_comp
#print axioms ASGinzburg.CyclicWord
#print axioms ASGinzburg.WordPolynomial
#print axioms ASGinzburg.CyclicPolynomial
#print axioms ASGinzburg.wordClass
#print axioms ASGinzburg.traceWord
#print axioms ASGinzburg.wordClass_append_swap
#print axioms ASGinzburg.traceWord_append_swap
#print axioms ASGinzburg.wordCutDegree
#print axioms ASGinzburg.wordCutDegree_append
#print axioms ASGinzburg.unique_cut_split
#print axioms ASGinzburg.reconstructAux
#print axioms ASGinzburg.reconstructAux_euler
#print axioms ASGinzburg.cyclicTrace
#print axioms ASGinzburg.cutReconstruction
#print axioms ASGinzburg.cut_euler_identity
#print axioms ASGinzburg.cut_normal_form
#print axioms ASGinzburg.path_word_cutDegree
#print axioms ASGinzburg.CutQuiver
#print axioms ASGinzburg.CutQuiver.Arrow
#print axioms ASGinzburg.CutQuiver.Vertex
#print axioms ASGinzburg.CutQuiver.LiftVertex
#print axioms ASGinzburg.CutQuiver.cutDegree
#print axioms ASGinzburg.CutQuiver.winding
#print axioms ASGinzburg.CutQuiver.height
#print axioms ASGinzburg.CutQuiver.periodNeZero
#print axioms ASGinzburg.CutQuiver.heightEquiv
#print axioms ASGinzburg.CutQuiver.heightEquiv_apply
#print axioms ASGinzburg.CutQuiver.height_bijective
#print axioms ASGinzburg.CutQuiver.shift
#print axioms ASGinzburg.CutQuiver.tau
#print axioms ASGinzburg.CutQuiver.liftedSource
#print axioms ASGinzburg.CutQuiver.liftedTarget
#print axioms ASGinzburg.CutQuiver.cutDegree_false
#print axioms ASGinzburg.CutQuiver.cutDegree_true
#print axioms ASGinzburg.CutQuiver.winding_pos
#print axioms ASGinzburg.CutQuiver.winding_lt_period
#print axioms ASGinzburg.CutQuiver.height_shift
#print axioms ASGinzburg.CutQuiver.height_tau
#print axioms ASGinzburg.CutQuiver.lifted_height_difference
#print axioms ASGinzburg.CutQuiver.lifted_arrow_increases_height
#print axioms ASGinzburg.CutQuiver.intermediate_in_interval
#print axioms ASGinzburg.CutQuiver.Path
#print axioms ASGinzburg.CutQuiver.Path.length
#print axioms ASGinzburg.CutQuiver.Path.cutDegree
#print axioms ASGinzburg.CutQuiver.Path.winding
#print axioms ASGinzburg.CutQuiver.Path.toList
#print axioms ASGinzburg.CutQuiver.Path.length_toList
#print axioms ASGinzburg.CutQuiver.Path.winding_eq
#print axioms ASGinzburg.CutQuiver.Path.winding_nonneg
#print axioms ASGinzburg.CutQuiver.Path.winding_pos_of_length_pos
#print axioms ASGinzburg.CutQuiver.Path.zero_cut_increases_vertex
#print axioms ASGinzburg.CutQuiver.Path.zero_cut_has_no_nonempty_cycle
#print axioms ASGinzburg.CutQuiver.Path.cut_one_cycle_winding
#print axioms ASGinzburg.derivativeAux
#print axioms ASGinzburg.derivativeWord
#print axioms ASGinzburg.derivativeAux_append
#print axioms ASGinzburg.derivativeWord_append_swap
#print axioms ASGinzburg.derivativeWord_rotate
#print axioms ASGinzburg.derivativeCyclicWord
#print axioms ASGinzburg.derivativeCyclicWord_mk
#print axioms ASGinzburg.cyclicDerivative
#print axioms ASGinzburg.prependTrace
#print axioms ASGinzburg.prependTrace_single
#print axioms ASGinzburg.cyclicDerivative_traceWord
#print axioms ASGinzburg.derivativeAux_reconstruction
#print axioms ASGinzburg.cyclicCutReconstruction
#print axioms ASGinzburg.ite_linearMap_apply
#print axioms ASGinzburg.cyclicCutReconstruction_traceWord
#print axioms ASGinzburg.cyclicCutReconstruction_comp_trace
#print axioms ASGinzburg.cut_cyclic_derivative_identity
#print axioms ASGinzburg.totalDimension
#print axioms ASGinzburg.dimension_table_eq_single
#print axioms ASGinzburg.total_dimension_single
#print axioms ASGinzburg.total_one_iff_single
#print axioms ASGinzburg.ext_dimension_delta
#print axioms ASGinzburg.CutQuiver.GinzburgArrow
#print axioms ASGinzburg.CutQuiver.GinzburgArrow.source
#print axioms ASGinzburg.CutQuiver.GinzburgArrow.target
#print axioms ASGinzburg.CutQuiver.GinzburgArrow.cohomologicalDegree
#print axioms ASGinzburg.CutQuiver.GinzburgArrow.cutDegree
#print axioms ASGinzburg.CutQuiver.GinzburgArrow.winding
#print axioms ASGinzburg.CutQuiver.GinzburgArrow.winding_pos
#print axioms ASGinzburg.CutQuiver.GinzburgArrow.winding_formula
#print axioms ASGinzburg.CutQuiver.GinzburgArrow.original_dual_winding_sum
#print axioms ASGinzburg.CutQuiver.GinzburgArrow.original_dual_cut_sum
#print axioms ASGinzburg.CutQuiver.GinzburgArrow.loop_differential_cohomological_degree
#print axioms ASGinzburg.positive_recurrence_unique
#print axioms ASGinzburg.quadraticHilbert
#print axioms ASGinzburg.quadraticHilbert_closed
#print axioms ASGinzburg.quadraticHilbert_double
#print axioms ASGinzburg.quadraticHilbert_third_difference
#print axioms ASGinzburg.quadraticHilbert_unique
#print axioms ASGinzburg.quadraticHilbert_polynomial_bound
#print axioms ASGinzburg.CutQuiver.Path.comp
#print axioms ASGinzburg.CutQuiver.Path.comp_nil
#print axioms ASGinzburg.CutQuiver.Path.nil_comp
#print axioms ASGinzburg.CutQuiver.Path.comp_assoc
#print axioms ASGinzburg.CutQuiver.Path.cutDegree_comp
#print axioms ASGinzburg.CutQuiver.Path.winding_comp
#print axioms ASGinzburg.CutQuiver.PathComponent
#print axioms ASGinzburg.CutQuiver.pathComp
#print axioms ASGinzburg.CutQuiver.pathId
#print axioms ASGinzburg.CutQuiver.pathComp_single
#print axioms ASGinzburg.CutQuiver.pathComp_id
#print axioms ASGinzburg.CutQuiver.id_pathComp
#print axioms ASGinzburg.CutQuiver.pathComp_assoc
#print axioms ASGinzburg.ZAlgebra.Obj
#print axioms ASGinzburg.ZAlgebra.objCategory
#print axioms ASGinzburg.ZAlgebra.objHomAdd
#print axioms ASGinzburg.ZAlgebra.objHomModule
#print axioms ASGinzburg.ZAlgebra.objPreadditive
#print axioms ASGinzburg.ZAlgebra.objLinear
#print axioms ASGinzburg.ZAlgebra.objOppositeHomModule
#print axioms ASGinzburg.ZAlgebra.objOppositeLinear
#print axioms ASGinzburg.ZAlgebra.representableLinear
#print axioms ASGinzburg.ZAlgebra.linearYonedaAdditive
#print axioms ASGinzburg.ZAlgebra.linearYonedaLinear
#print axioms ASGinzburg.ZAlgebra.rightModuleProperty
#print axioms ASGinzburg.ZAlgebra.RightModule
#print axioms ASGinzburg.ZAlgebra.representable
#print axioms ASGinzburg.ZAlgebra.representableHomEquiv
#print axioms ASGinzburg.ZAlgebra.representableHom_vanishes
#print axioms ASGinzburg.ZAlgebra.scalarEndEquiv
#print axioms ASGinzburg.ZAlgebra.representableEnd_finrank
#print axioms ASGinzburg.ZAlgebra.rightModuleProperty_closedUnderLimits
#print axioms ASGinzburg.ZAlgebra.rightModuleProperty_closedUnderColimits
#print axioms ASGinzburg.ZAlgebra.rightModuleHasLimitsOfShape
#print axioms ASGinzburg.ZAlgebra.rightModuleHasColimitsOfShape
#print axioms ASGinzburg.ZAlgebra.rightModuleInclusionCreatesLimitsOfShape
#print axioms ASGinzburg.ZAlgebra.rightModuleInclusionCreatesColimitsOfShape
#print axioms ASGinzburg.ZAlgebra.rightModuleHasFiniteProducts
#print axioms ASGinzburg.ZAlgebra.rightModuleCoimageImageComparisonIsIso
#print axioms ASGinzburg.ZAlgebra.rightModuleAbelian
#print axioms ASGinzburg.ZAlgebra.rightModuleInclusionPreservesFiniteLimits
#print axioms ASGinzburg.ZAlgebra.rightModuleInclusionPreservesFiniteColimits
#print axioms ASGinzburg.ZAlgebra.rightModuleGenerators
#print axioms ASGinzburg.ZAlgebra.freeRightModule
#print axioms ASGinzburg.ZAlgebra.freeRightModuleπ
#print axioms ASGinzburg.ZAlgebra.freeRightModuleProjective
#print axioms ASGinzburg.ZAlgebra.freeRightModuleπEpi
#print axioms ASGinzburg.ZAlgebra.rightModuleEnoughProjectives
#print axioms ASGinzburg.ZAlgebra.rightModuleProjectiveResolution
#print axioms ASGinzburg.ZAlgebra.rightModuleProjectiveResolution_exactAt_succ
#print axioms ASGinzburg.ZAlgebra.rightModuleHasExt
#print axioms ASGinzburg.ZAlgebra.representableExtZeroEquiv
#print axioms ASGinzburg.ZAlgebra.representable_higher_ext_eq_zero
#print axioms ASGinzburg.ZAlgebra.shiftedHomModule
#print axioms ASGinzburg.ZAlgebra.rightModuleDerivedLinear
#print axioms ASGinzburg.ZAlgebra.rightModuleDerivedQhLinear
#print axioms ASGinzburg.ZAlgebra.rightModuleDerivedSingleLinear
#print axioms ASGinzburg.ZAlgebra.rightModuleExtHomAddEquiv
#print axioms ASGinzburg.ZAlgebra.rightModuleExtModule
#print axioms ASGinzburg.ZAlgebra.rightModuleExtHomLinearEquiv
#print axioms ASGinzburg.ZAlgebra.rightModuleExt_mk₀_smul
#print axioms ASGinzburg.ZAlgebra.rightModuleExtZeroLinearEquiv
#print axioms ASGinzburg.ZAlgebra.representableExtZeroLinearEquiv
#print axioms ASGinzburg.ZAlgebra.rightModuleDerivedShiftLinear
#print axioms ASGinzburg.ZAlgebra.rightModuleExt_smul_comp
#print axioms ASGinzburg.ZAlgebra.rightModuleExt_comp_smul
#print axioms ASGinzburg.ZAlgebra.rightModuleExtBoundary
#print axioms ASGinzburg.ZAlgebra.rightModuleExtBoundary_bijective
#print axioms ASGinzburg.ZAlgebra.rightModuleExtDimensionShift
#print axioms ASGinzburg.ZAlgebra.rightModuleExtZeroBoundary_bijective
#print axioms ASGinzburg.ZAlgebra.rightModuleExtZeroDimensionShift
#print axioms ASGinzburg.ZAlgebra.rightModuleEvaluation
#print axioms ASGinzburg.ZAlgebra.rightModuleEvaluationAdditive
#print axioms ASGinzburg.ZAlgebra.rightModuleEvaluationPreservesFiniteLimits
#print axioms ASGinzburg.ZAlgebra.rightModuleEvaluationPreservesFiniteColimits
#print axioms ASGinzburg.ZAlgebra.rightModuleInclusionPreservesHomology
#print axioms ASGinzburg.ZAlgebra.rightModuleEvaluationPreservesHomology
#print axioms ASGinzburg.ZAlgebra.rightModuleKernelObjIso
#print axioms ASGinzburg.ZAlgebra.rightModuleCokernelObjIso
#print axioms ASGinzburg.ZAlgebra.rightModuleHomologyObjIso
#print axioms ASGinzburg.ZAlgebra.rightModule_exact_iff_inclusion
#print axioms ASGinzburg.ZAlgebra.rightModuleKernelObjIso_inv_ι
#print axioms ASGinzburg.ZAlgebra.rightModuleCokernelObjIso_π_hom
#print axioms ASGinzburg.ZAlgebra.rightModule_mono_iff
#print axioms ASGinzburg.ZAlgebra.rightModule_epi_iff
#print axioms ASGinzburg.ZAlgebra.rightModule_mono_iff_injective
#print axioms ASGinzburg.ZAlgebra.rightModule_epi_iff_surjective
#print axioms ASGinzburg.ZAlgebra.rightModule_exact_iff
#print axioms ASGinzburg.ZAlgebra.rightModule_exact_iff_range_eq_ker
#print axioms ASGinzburg.ZAlgebra.rightModule_shortExact_iff
#print axioms ASGinzburg.ZAlgebra.IsMinimalMorphism
#print axioms ASGinzburg.ZAlgebra.isMinimalMorphism_iff_range_le
#print axioms ASGinzburg.ZAlgebra.minimalMorphismLift
#print axioms ASGinzburg.ZAlgebra.minimalMorphismLift_inclusion
#print axioms ASGinzburg.ZAlgebra.isMinimalMorphism_of_factor
#print axioms ASGinzburg.ZAlgebra.isMinimalMorphism_iff_factors
#print axioms ASGinzburg.ZAlgebra.isMinimalMorphism_zero
#print axioms ASGinzburg.ZAlgebra.isMinimalMorphism_comp_left
#print axioms ASGinzburg.ZAlgebra.isMinimalMorphism_comp_right
#print axioms ASGinzburg.ZAlgebra.representableToElement
#print axioms ASGinzburg.ZAlgebra.representableYonedaEquiv
#print axioms ASGinzburg.ZAlgebra.representableYonedaEquiv_apply
#print axioms ASGinzburg.ZAlgebra.representableYonedaEquiv_comp
#print axioms ASGinzburg.ZAlgebra.representableYonedaEquiv_symm_app
#print axioms ASGinzburg.ZAlgebra.representableProjective
#print axioms ASGinzburg.ZAlgebra.positiveActionSpan_action_mem
#print axioms ASGinzburg.ZAlgebra.rightModuleRadical
#print axioms ASGinzburg.ZAlgebra.positiveActionSpan_map_mem
#print axioms ASGinzburg.ZAlgebra.rightModuleRadicalMap
#print axioms ASGinzburg.ZAlgebra.rightModuleRadicalMap_inclusion
#print axioms ASGinzburg.ZAlgebra.rightModuleRadicalFunctor
#print axioms ASGinzburg.ZAlgebra.rightModuleRadicalFunctorAdditive
#print axioms ASGinzburg.ZAlgebra.rightModuleRadicalFunctorLinear
#print axioms ASGinzburg.ZAlgebra.rightModuleRadical_representable_component
#print axioms ASGinzburg.ZAlgebra.positiveActionSpan_simple_eq_bot
#print axioms ASGinzburg.ZAlgebra.radical_inclusion_comp_simple_eq_zero
#print axioms ASGinzburg.ZAlgebra.minimalMorphism_comp_simple_eq_zero
#print axioms ASGinzburg.ZAlgebra.RightSubmodule
#print axioms ASGinzburg.ZAlgebra.RightSubmodule.presheaf
#print axioms ASGinzburg.ZAlgebra.RightSubmodule.presheafAdditive
#print axioms ASGinzburg.ZAlgebra.RightSubmodule.presheafLinear
#print axioms ASGinzburg.ZAlgebra.RightSubmodule.object
#print axioms ASGinzburg.ZAlgebra.RightSubmodule.inclusion
#print axioms ASGinzburg.ZAlgebra.RightSubmodule.inclusionMono
#print axioms ASGinzburg.ZAlgebra.RightSubmodule.quotient
#print axioms ASGinzburg.ZAlgebra.RightSubmodule.quotientπ
#print axioms ASGinzburg.ZAlgebra.RightSubmodule.quotientπEpi
#print axioms ASGinzburg.ZAlgebra.RightSubmodule.quotientShortComplex
#print axioms ASGinzburg.ZAlgebra.RightSubmodule.quotientShortExact
#print axioms ASGinzburg.ZAlgebra.representableRadical
#print axioms ASGinzburg.ZAlgebra.positiveActionSpan
#print axioms ASGinzburg.ZAlgebra.representableRadical_eq_positiveActionSpan
#print axioms ASGinzburg.ZAlgebra.simpleRightModule
#print axioms ASGinzburg.ZAlgebra.simpleRightModuleπ
#print axioms ASGinzburg.ZAlgebra.simpleRightModuleπEpi
#print axioms ASGinzburg.ZAlgebra.representableRadical_diagonal_zero
#print axioms ASGinzburg.ZAlgebra.simpleRightModuleDiagonalIso
#print axioms ASGinzburg.ZAlgebra.simpleRightModule_off_diagonal
#print axioms ASGinzburg.ZAlgebra.simpleRightModule_diagonal_finrank
#print axioms ASGinzburg.ZAlgebra.simpleRightModuleDiagonalSimple
#print axioms ASGinzburg.ZAlgebra.simpleRightModule_hom_eq_zero_iff
#print axioms ASGinzburg.ZAlgebra.simpleRightModuleSimple
#print axioms ASGinzburg.ZAlgebra.simpleRightModule_shortExact
#print axioms ASGinzburg.ArrowSpace333
#print axioms ASGinzburg.CubicTensor333
#print axioms ASGinzburg.Triple333
#print axioms ASGinzburg.CubicCoefficients333
#print axioms ASGinzburg.CutRelations333
#print axioms ASGinzburg.cubicBasis333
#print axioms ASGinzburg.cubicCoordinates333
#print axioms ASGinzburg.cutRelationCoordinates333
#print axioms ASGinzburg.tensorToCutRelations333
#print axioms ASGinzburg.tensor_recovered_from_cut_relations333
#print axioms ASGinzburg.cubicTensor333_finrank
#print axioms ASGinzburg.arrowBasisChange333
#print axioms ASGinzburg.arrowBasisChange333_tmul
#print axioms ASGinzburg.TopCohomology
#print axioms ASGinzburg.map_from_zero_domain_eq_zero
#print axioms ASGinzburg.topCohomologyEquiv
#print axioms ASGinzburg.topCohomology_finrank
#print axioms ASGinzburg.topCohomology_field_finrank
#print axioms ASGinzburg.triangle333
#print axioms ASGinzburg.triangleX
#print axioms ASGinzburg.triangleY
#print axioms ASGinzburg.triangleZ
#print axioms ASGinzburg.triangleX_cut
#print axioms ASGinzburg.triangleY_cut
#print axioms ASGinzburg.triangleZ_cut
#print axioms ASGinzburg.triangle_arrow_winding
#print axioms ASGinzburg.triangle_path_winding
#print axioms ASGinzburg.triangle_cut_one_cycle_is_cubic
#print axioms ASGinzburg.triangle_same_winding_as_arrow_is_linear
#print axioms ASGinzburg.trianglePotential
#print axioms ASGinzburg.trianglePotential_cut_derivative_identity
#print axioms ASGinzburg.ZAlgebra.InWindow
#print axioms ASGinzburg.ZAlgebra.InWindow.mono
#print axioms ASGinzburg.ZAlgebra.WindowSystem
#print axioms ASGinzburg.ZAlgebra.WindowSystem.globalMap
#print axioms ASGinzburg.ZAlgebra.WindowSystem.globalMap_eq_window
#print axioms ASGinzburg.ZAlgebra.WindowSystem.periodIso
#print axioms ASGinzburg.ZAlgebra.WindowSystem.isPeriodic
#print axioms ASGinzburg.ZAlgebra
#print axioms ASGinzburg.ZAlgebra.PeriodIso
#print axioms ASGinzburg.ZAlgebra.IsPeriodic
#print axioms ASGinzburg.ZAlgebra.LinearSubcategory
#print axioms ASGinzburg.ZAlgebra.products
#print axioms ASGinzburg.ZAlgebra.generated_of_decomposition
