import work.ASGinzburgDraft.ASCutGradedModuleEquivalence
import work.ASGinzburgDraft.ASCutGradedResolutions
import work.ASGinzburgDraft.ASCutGradedVertexExt
import work.ASGinzburgDraft.LinearEquivalenceAdjunction
import work.ASGinzburgDraft.PeriodCutComponentRegrouping
import work.ASGinzburgDraft.PeriodCutComponentTargetSum
import work.ASGinzburgDraft.PeriodCutComponentTotalRecomposition
import work.ASGinzburgDraft.PeriodCutCornerComponentComparison
import work.ASGinzburgDraft.PeriodCutCornerTotalActions
import work.ASGinzburgDraft.PeriodCutDegreeComponentRecomposition
import work.ASGinzburgDraft.PeriodCutGradedCornerActions
import work.ASGinzburgDraft.PeriodCutGradedFunctorFaithful
import work.ASGinzburgDraft.PeriodCutGradedModuleAbelian
import work.ASGinzburgDraft.PeriodCutGradedModuleComponents
import work.ASGinzburgDraft.PeriodCutGradedModuleEquivalence
import work.ASGinzburgDraft.PeriodCutGradedModuleExt
import work.ASGinzburgDraft.PeriodCutGradedModuleYoneda
import work.ASGinzburgDraft.PeriodCutGradedSimpleSpaces
import work.ASGinzburgDraft.PeriodCutModuleComparisonValues
import work.ASGinzburgDraft.PeriodCutModuleComponentTotalEquiv
import work.ASGinzburgDraft.PeriodCutModuleDegreeComponents
import work.ASGinzburgDraft.PeriodCutModuleDegreeVertexAction
import work.ASGinzburgDraft.PeriodCutModuleIdempotentAction
import work.ASGinzburgDraft.PeriodCutModuleMatrixEntryActions
import work.ASGinzburgDraft.PeriodCutModuleObjectComparison
import work.ASGinzburgDraft.PeriodCutModuleUnitNaturality
import work.ASGinzburgDraft.PeriodCutModuleVertexProjections
import work.ASGinzburgDraft.PeriodCutRecoveredComponentActions
import work.ASGinzburgDraft.PeriodCutRecoveredComponentMorphisms
import work.ASGinzburgDraft.PeriodCutRecoveredCounitNaturalIso
import work.ASGinzburgDraft.PeriodCutRecoveredGradedModuleIso
import work.ASGinzburgDraft.PeriodCutRecoveredInverseGrading
import work.ASGinzburgDraft.PeriodCutRecoveredModuleFunctor
import work.ASGinzburgDraft.PeriodCutRecoveredModuleUnitIso
import work.ASGinzburgDraft.PeriodCutRecoveredRightModules
import work.ASGinzburgDraft.PeriodCutRecoveredTotalComparison
import work.ASGinzburgDraft.PeriodCutRecoveredTotalCornerActions
import work.ASGinzburgDraft.PeriodCutRecoveredTotalGrading
import work.ASGinzburgDraft.PeriodCutRecoveredTotalHomogeneousActions
import work.ASGinzburgDraft.PeriodCutRecoveredTotalRActions
import work.ASGinzburgDraft.PeriodCutRecoveredUnitNaturalIso
import work.ASGinzburgDraft.PeriodIntegerCornerAbsorption

#print axioms ASGinzburg.ZAlgebra.ASRegular.cutGradedModuleEquivalence
#print axioms ASGinzburg.ZAlgebra.ASRegular.cutGradedModuleEquivalence_functor_additive
#print axioms ASGinzburg.ZAlgebra.ASRegular.cutGradedModuleEquivalence_functor_linear
#print axioms ASGinzburg.ZAlgebra.ASRegular.cutGradedModuleEquivalence_inverse_additive
#print axioms ASGinzburg.ZAlgebra.ASRegular.cutGradedExtLinearEquiv
#print axioms ASGinzburg.ZAlgebra.ASRegular.cutGradedProjective_projective
#print axioms ASGinzburg.ZAlgebra.ASRegular.cutGradedSimpleProjectiveResolution
#print axioms ASGinzburg.ZAlgebra.ASRegular.cutGradedSimpleProjectiveResolution_isZero_ge_four
#print axioms ASGinzburg.ZAlgebra.ASRegular.cutGradedSimple
#print axioms ASGinzburg.ZAlgebra.ASRegular.cutGradedProjective
#print axioms ASGinzburg.ZAlgebra.ASRegular.cutGradedVertexExtLinearEquiv
#print axioms ASGinzburg.ZAlgebra.ASRegular.cutGradedExtThreeEquiv
#print axioms ASGinzburg.ZAlgebra.ASRegular.cutGradedExt_other_eq_zero
#print axioms ASGinzburg.equivalenceAdjunctionHomLinearEquiv
#print axioms ASGinzburg.ZAlgebra.PeriodIso.CutGradedRightModule.componentRegroupEquiv_apply
#print axioms ASGinzburg.ZAlgebra.PeriodIso.CutGradedRightModule.componentRegroupEquiv_lof
#print axioms ASGinzburg.ZAlgebra.PeriodIso.sum_cutHomogeneousComponentLinear_target
#print axioms ASGinzburg.ZAlgebra.PeriodIso.CutGradedRightModule.totalDegreeComponentEquiv_symm_lof
#print axioms ASGinzburg.ZAlgebra.PeriodIso.CutGradedRightModule.componentTotalEquiv_symm_lof
#print axioms ASGinzburg.ZAlgebra.PeriodIso.CutGradedRightModule.componentRecomposition
#print axioms ASGinzburg.ZAlgebra.PeriodIso.CutGradedRightModule.componentRecomposition_eq_symm
#print axioms ASGinzburg.ZAlgebra.PeriodIso.CutGradedRightModule.componentRecomposition_bijective
#print axioms ASGinzburg.ZAlgebra.PeriodIso.cornerComponentInjection
#print axioms ASGinzburg.ZAlgebra.PeriodIso.cornerComponentProjection
#print axioms ASGinzburg.ZAlgebra.PeriodIso.cornerComponentProjection_injection
#print axioms ASGinzburg.ZAlgebra.PeriodIso.cornerComponentInjection_projection
#print axioms ASGinzburg.ZAlgebra.PeriodIso.cornerComponentEquiv
#print axioms ASGinzburg.ZAlgebra.PeriodIso.cutRightRepresentation_corner_lof
#print axioms ASGinzburg.ZAlgebra.PeriodIso.CutGradedRightModule.degreeComponentEquiv_symm_lof_val
#print axioms ASGinzburg.ZAlgebra.PeriodIso.CutGradedRightModule.representation_mul_apply
#print axioms ASGinzburg.ZAlgebra.PeriodIso.CutGradedRightModule.integerCorner_action_mem_grade
#print axioms ASGinzburg.ZAlgebra.PeriodIso.cornerCoordinateObject_surjective
#print axioms ASGinzburg.ZAlgebra.PeriodIso.cornerGradedModuleFunctorFaithful
#print axioms ASGinzburg.ZAlgebra.PeriodIso.cornerGradedModuleEquivalence_functor_additive
#print axioms ASGinzburg.ZAlgebra.PeriodIso.cornerGradedModuleEquivalence_inverse_additive
#print axioms ASGinzburg.ZAlgebra.PeriodIso.recoveredModuleFunctorIsEquivalence
#print axioms ASGinzburg.ZAlgebra.PeriodIso.cutGradedModuleHasFiniteProducts
#print axioms ASGinzburg.ZAlgebra.PeriodIso.cutGradedModuleAbelian
#print axioms ASGinzburg.ZAlgebra.PeriodIso.cutGradedModuleEnoughProjectives
#print axioms ASGinzburg.ZAlgebra.PeriodIso.cutGradedModuleHasExt
#print axioms ASGinzburg.ZAlgebra.PeriodIso.CutGradedRightModule.vertexProjection
#print axioms ASGinzburg.ZAlgebra.PeriodIso.CutGradedRightModule.vertexProjection_idempotent
#print axioms ASGinzburg.ZAlgebra.PeriodIso.CutGradedRightModule.vertexProjection_preserves_grade
#print axioms ASGinzburg.ZAlgebra.PeriodIso.CutGradedRightModule.componentSubmodule
#print axioms ASGinzburg.ZAlgebra.PeriodIso.CutGradedRightModule.mem_componentSubmodule_iff
#print axioms ASGinzburg.ZAlgebra.PeriodIso.cornerGradedModuleEquivalence
#print axioms ASGinzburg.ZAlgebra.PeriodIso.cornerGradedModuleEquivalence_functor_linear
#print axioms ASGinzburg.ZAlgebra.PeriodIso.cornerGradedModuleEquivalence_inverse_linear
#print axioms ASGinzburg.ZAlgebra.PeriodIso.cutGradedModuleExtModule
#print axioms ASGinzburg.ZAlgebra.PeriodIso.cornerGradedModuleExtAddEquiv
#print axioms ASGinzburg.ZAlgebra.PeriodIso.cornerGradedModuleExtLinearEquiv
#print axioms ASGinzburg.ZAlgebra.PeriodIso.cornerGradedRepresentable
#print axioms ASGinzburg.ZAlgebra.PeriodIso.cornerGradedRepresentableYonedaEquiv
#print axioms ASGinzburg.ZAlgebra.PeriodIso.cornerSimpleSpace_off
#print axioms ASGinzburg.ZAlgebra.PeriodIso.cornerSimpleTotalSpaceEquiv
#print axioms ASGinzburg.ZAlgebra.PeriodIso.cornerSimpleTotalSpace_finrank
#print axioms ASGinzburg.ZAlgebra.PeriodIso.cornerComponentEquiv_transport_val
#print axioms ASGinzburg.ZAlgebra.PeriodIso.cornerAtObjectEquiv_coordinate_val
#print axioms ASGinzburg.ZAlgebra.PeriodIso.CutGradedRightModule.degreeComponentEquiv
#print axioms ASGinzburg.ZAlgebra.PeriodIso.CutGradedRightModule.totalDegreeComponentEquiv
#print axioms ASGinzburg.ZAlgebra.PeriodIso.CutGradedRightModule.componentRegroupEquiv
#print axioms ASGinzburg.ZAlgebra.PeriodIso.CutGradedRightModule.componentTotalEquiv
#print axioms ASGinzburg.ZAlgebra.PeriodIso.CutGradedRightModule.degreeVertexMap
#print axioms ASGinzburg.ZAlgebra.PeriodIso.CutGradedRightModule.degreeVertexSum
#print axioms ASGinzburg.ZAlgebra.PeriodIso.CutGradedRightModule.degreeVertexSum_map
#print axioms ASGinzburg.ZAlgebra.PeriodIso.CutGradedRightModule.degreeVertexMap_sum
#print axioms ASGinzburg.ZAlgebra.PeriodIso.CutGradedRightModule.degreeVertexEquiv
#print axioms ASGinzburg.ZAlgebra.PeriodIso.cutRightRepresentation_vertex_degreeInsertion
#print axioms ASGinzburg.ZAlgebra.PeriodIso.cutRightRepresentation_vertex_lof_self
#print axioms ASGinzburg.ZAlgebra.PeriodIso.cutRightRepresentation_vertex_lof_off
#print axioms ASGinzburg.ZAlgebra.PeriodIso.cutMatrixComponent_target_ne
#print axioms ASGinzburg.ZAlgebra.PeriodIso.cutHomogeneousRightOperator_component_lof
#print axioms ASGinzburg.ZAlgebra.PeriodIso.cutHomogeneousRightOperator_component_lof_off
#print axioms ASGinzburg.ZAlgebra.PeriodIso.cornerCoordinateObject_inverse
#print axioms ASGinzburg.ZAlgebra.PeriodIso.cornerAtObjectEquiv
#print axioms ASGinzburg.ZAlgebra.PeriodIso.cornerAtObjectEquiv_naturality
#print axioms ASGinzburg.ZAlgebra.PeriodIso.CutGradedRightModule.vertexProjection_orthogonal
#print axioms ASGinzburg.ZAlgebra.PeriodIso.CutGradedRightModule.sum_vertexProjection
#print axioms ASGinzburg.ZAlgebra.PeriodIso.CutGradedRightModule.sum_vertexProjection_apply
#print axioms ASGinzburg.ZAlgebra.PeriodIso.CutGradedRightModule.vertexProjection_mem_component
#print axioms ASGinzburg.ZAlgebra.PeriodIso.CutGradedRightModule.corner_action_mem_component
#print axioms ASGinzburg.ZAlgebra.PeriodIso.CutGradedRightModule.recoveredComponentAction
#print axioms ASGinzburg.ZAlgebra.PeriodIso.CutGradedRightModule.recoveredComponentAction_comp
#print axioms ASGinzburg.ZAlgebra.PeriodIso.CutGradedRightModule.recoveredComponentAction_id
#print axioms ASGinzburg.ZAlgebra.PeriodIso.CutGradedRightModule.map_mem_componentSubmodule
#print axioms ASGinzburg.ZAlgebra.PeriodIso.CutGradedRightModule.recoveredComponentLinearMap
#print axioms ASGinzburg.ZAlgebra.PeriodIso.CutGradedRightModule.recoveredCounitNaturalIso
#print axioms ASGinzburg.ZAlgebra.PeriodIso.CutGradedRightModule.recoveredGradedModuleIso
#print axioms ASGinzburg.ZAlgebra.PeriodIso.CutGradedRightModule.recoveredTotalEquiv_degreeInsertion
#print axioms ASGinzburg.ZAlgebra.PeriodIso.CutGradedRightModule.recoveredTotalEquiv_symm_mem_grade
#print axioms ASGinzburg.ZAlgebra.PeriodIso.CutGradedRightModule.recoveredModuleMap
#print axioms ASGinzburg.ZAlgebra.PeriodIso.CutGradedRightModule.recoveredModuleFunctor
#print axioms ASGinzburg.ZAlgebra.PeriodIso.CutGradedRightModule.recoveredModuleFunctorAdditive
#print axioms ASGinzburg.ZAlgebra.PeriodIso.CutGradedRightModule.recoveredModuleFunctorLinear
#print axioms ASGinzburg.ZAlgebra.PeriodIso.cornerRecoveredModulePresheafIso
#print axioms ASGinzburg.ZAlgebra.PeriodIso.cornerRecoveredModuleIso
#print axioms ASGinzburg.ZAlgebra.PeriodIso.CutGradedRightModule.recoveredRightPresheaf
#print axioms ASGinzburg.ZAlgebra.PeriodIso.CutGradedRightModule.recoveredRightPresheafAdditive
#print axioms ASGinzburg.ZAlgebra.PeriodIso.CutGradedRightModule.recoveredRightPresheafLinear
#print axioms ASGinzburg.ZAlgebra.PeriodIso.CutGradedRightModule.recoveredRightModule
#print axioms ASGinzburg.ZAlgebra.PeriodIso.CutGradedRightModule.recoveredCoordinateSpaceEquiv
#print axioms ASGinzburg.ZAlgebra.PeriodIso.CutGradedRightModule.recoveredCoordinateTotalEquiv
#print axioms ASGinzburg.ZAlgebra.PeriodIso.CutGradedRightModule.recoveredCoordinateTotalEquiv_lof
#print axioms ASGinzburg.ZAlgebra.PeriodIso.CutGradedRightModule.recoveredTotalEquiv
#print axioms ASGinzburg.ZAlgebra.PeriodIso.CutGradedRightModule.recoveredTotalEquiv_lof
#print axioms ASGinzburg.ZAlgebra.PeriodIso.CutGradedRightModule.recoveredCoordinateSpaceEquiv_val
#print axioms ASGinzburg.ZAlgebra.PeriodIso.CutGradedRightModule.recoveredTotalEquiv_corner_lof
#print axioms ASGinzburg.ZAlgebra.PeriodIso.CutGradedRightModule.recoveredTotalEquiv_degreeInsertion_mem
#print axioms ASGinzburg.ZAlgebra.PeriodIso.CutGradedRightModule.recoveredTotalEquiv_mem_grade
#print axioms ASGinzburg.ZAlgebra.PeriodIso.CutGradedRightModule.recoveredDegreeSpaceEquiv
#print axioms ASGinzburg.ZAlgebra.PeriodIso.CutGradedRightModule.recoveredDegreeSpaceEquiv_lof
#print axioms ASGinzburg.ZAlgebra.PeriodIso.CutGradedRightModule.representation_sum_apply
#print axioms ASGinzburg.ZAlgebra.PeriodIso.CutGradedRightModule.recoveredTotalEquiv_lof_vertex_fixed
#print axioms ASGinzburg.ZAlgebra.PeriodIso.CutGradedRightModule.recoveredTotalEquiv_homogeneous_action
#print axioms ASGinzburg.ZAlgebra.PeriodIso.CutGradedRightModule.recoveredTotalEquiv_representation_action
#print axioms ASGinzburg.ZAlgebra.PeriodIso.CutGradedRightModule.recoveredTotalEquiv_symm_representation_action
#print axioms ASGinzburg.ZAlgebra.PeriodIso.cornerRecoveredUnitNaturalIso
#print axioms ASGinzburg.ZAlgebra.PeriodIso.integerCorner_target_absorption
#print axioms ASGinzburg.ZAlgebra.PeriodIso.integerCorner_source_absorption
