import ASGinzburg.LinearIdealProducts

/-! Ideals generated by actual homogeneous component relations are the
intersection of all genuine two-sided linear ideals containing them. -/
namespace ASGinzburg.ZAlgebra.LinearIdeal
universe u v
variable {k : Type u} [Field k] {B : ZAlgebra.{u,v} k}

def generated (R : ∀ i j, Set (B.Hom i j)) : B.LinearIdeal where
  hom i j := ⨅ (I : B.LinearIdeal) (_ : ∀ i j, R i j ⊆ I.hom i j), I.hom i j
  comp_left := by
    intro i j l f hf g
    simp only [Submodule.mem_iInf] at hf ⊢
    intro I hI
    exact I.comp_left (hf I hI) g
  comp_right := by
    intro i j l g hg f
    simp only [Submodule.mem_iInf] at hg ⊢
    intro I hI
    exact I.comp_right (hg I hI) f

theorem subset_generated (R : ∀ i j, Set (B.Hom i j)) (i j : ℤ) :
    R i j ⊆ (generated R).hom i j := by
  intro f hf
  change f ∈ ⨅ (I : B.LinearIdeal) (_ : ∀ i j, R i j ⊆ I.hom i j), I.hom i j
  simp only [Submodule.mem_iInf]
  intro I hI
  exact hI i j hf

theorem generated_le (R : ∀ i j, Set (B.Hom i j)) (I : B.LinearIdeal)
    (hI : ∀ i j, R i j ⊆ I.hom i j) (i j : ℤ) :
    (generated R).hom i j ≤ I.hom i j :=
  iInf_le_of_le I (iInf_le_of_le hI le_rfl)

end ASGinzburg.ZAlgebra.LinearIdeal
