import ASGinzburg.PathLinearIdeals
import ASGinzburg.GinzburgBoundaryProducts

/-! The genuine finite quiver Jacobian ideal generated by its path-valued
cyclic derivatives. Every such relation is an actual degree zero boundary. -/
namespace ASGinzburg.CutQuiver
universe u
variable (Q : CutQuiver) (k : Type u) [Field k]

def pathJacobianRelations (φ : Q.Potential k) (u v : Q.Vertex) : Set (Q.PathComponent k u v) :=
  {x | ∃ a : Q.Arrow, ∃ hu : Q.target a=u, ∃ hv : Q.source a=v,
    Q.transportPathComponent k hu hv (Q.pathCyclicDerivative k a φ)=x}

noncomputable def pathJacobianIdeal (φ : Q.Potential k) : Q.PathLinearIdeal k :=
  Q.generatedPathIdeal k (Q.pathJacobianRelations k φ)

theorem pathCyclicDerivative_mem_pathJacobianIdeal (φ : Q.Potential k) (a : Q.Arrow) :
    Q.pathCyclicDerivative k a φ ∈ (Q.pathJacobianIdeal k φ).hom (Q.target a) (Q.source a) :=
  Q.subset_generatedPathIdeal k _ _ _ ⟨a,rfl,rfl,rfl⟩

noncomputable def ginzburgBoundaryIdeal (φ : Q.Potential k) : Q.PathLinearIdeal k where
  hom := Q.ginzburgBoundarySpace k φ
  comp_left := fun hf g => Q.ginzburgBoundarySpace_comp_left k φ hf g
  comp_right := fun hg f => Q.ginzburgBoundarySpace_comp_right k φ hg f

theorem pathCyclicDerivative_mem_boundary (φ : Q.Potential k) (a : Q.Arrow) :
    Q.pathCyclicDerivative k a φ ∈ Q.ginzburgBoundarySpace k φ (Q.target a) (Q.source a) := by
  apply (Q.ginzburgBoundarySpace_mem_iff k φ _ _ _).mpr
  refine ⟨⟨Finsupp.single (Q.dualGinzburgArrowPath a) 1,?_⟩,?_⟩
  · exact Finsupp.single_mem_supported _ _ rfl
  · exact Q.ginzburgDifferential_dualArrow k φ a

theorem pathJacobianIdeal_le_boundary (φ : Q.Potential k) (u v : Q.Vertex) :
    (Q.pathJacobianIdeal k φ).hom u v ≤ Q.ginzburgBoundarySpace k φ u v := by
  apply Q.generatedPathIdeal_le k _ (Q.ginzburgBoundaryIdeal k φ) _ u v
  intro u v f hf
  obtain ⟨a,hu,hv,rfl⟩ := hf
  subst u v
  exact Q.pathCyclicDerivative_mem_boundary k φ a

end ASGinzburg.CutQuiver
