import ASGinzburg.ASZeroCutRingRelationGenerators
import ASGinzburg.TwoSidedSpanRingEquiv

/-! The actual non-cut relation ideal and presentation kernel are
generated by the genuine finite chosen non-cut relation embeddings. -/
namespace ASGinzburg.ZAlgebra
universe u
variable {k : Type u} [Field k] (A : ZAlgebra.{u,u} k) (Q : CutQuiver)

theorem ASRegular.foundationZeroCutRelationIdeal_eq_span (hAS : A.ASRegular Q) :
    hAS.foundationZeroCutRelationIdeal A Q=
      (TwoSidedIdeal.span (hAS.foundationZeroCutRingRelationGenerators A Q)).asIdeal := by
  ext x
  change Q.zeroCutFoundationRingAlgEquiv k x ∈
    (hAS.foundationRelationIdeal A Q).foundationIdeal Q ↔
      x ∈ (TwoSidedIdeal.span (hAS.foundationZeroCutRingRelationGenerators A Q)).asIdeal
  rw [hAS.foundationRingRelationIdeal_eq_span A Q,
    ←hAS.foundationZeroCutRingRelationGenerators_image A Q]
  exact ASGinzburg.ringEquiv_mem_twoSidedSpan_image_iff
    (Q.zeroCutFoundationRingAlgEquiv k).toRingEquiv
    (hAS.foundationZeroCutRingRelationGenerators A Q) x

theorem ASRegular.foundationZeroCutKernel_eq_span (hAS : A.ASRegular Q) :
    RingHom.ker (hAS.foundationZeroCutPresentation A Q).toRingHom=
      (TwoSidedIdeal.span (hAS.foundationZeroCutRingRelationGenerators A Q)).asIdeal := by
  rw [←hAS.foundationZeroCutRelationIdeal_eq_kernel A Q,hAS.foundationZeroCutRelationIdeal_eq_span A Q]

noncomputable def ASRegular.foundationZeroCutGeneratedQuotientAlgEquiv (hAS : A.ASRegular Q) :
    (Q.ZeroCutPathRing k ⧸
      (TwoSidedIdeal.span (hAS.foundationZeroCutRingRelationGenerators A Q)).asIdeal) ≃ₐ[k]
      A.FoundationAlgebra Q :=
  (Ideal.quotientEquivAlgOfEq k (hAS.foundationZeroCutRelationIdeal_eq_span A Q).symm).trans
    (hAS.foundationZeroCutQuotientAlgEquiv A Q)

end ASGinzburg.ZAlgebra
