import ASGinzburg.RightModuleBoundedGeneration
import ASGinzburg.RightModuleEnoughProjectives
import Mathlib.LinearAlgebra.Basis.VectorSpace

/-! A bounded-above directed right module admits a genuine projective
presentation generated by chosen bases of its actual radical quotient
components. Surjectivity follows from the proved graded Nakayama lemma. -/
namespace ASGinzburg.ZAlgebra
open CategoryTheory CategoryTheory.Limits Opposite
universe u v
variable {k : Type u} [Field k] (A : ZAlgebra.{u,v} k)

abbrev RightModuleTopSpace (M : A.RightModule) (i : ℤ) :=
  (A.rightModuleEvaluation i).obj M ⧸ A.positiveActionSpan M i

abbrev rightTopBasisIndex (M : A.RightModule) :=
  Σ i : ℤ, Module.Free.ChooseBasisIndex k (A.RightModuleTopSpace M i)

noncomputable def rightTopBasisLift (M : A.RightModule) (g : A.rightTopBasisIndex M) :
    (A.rightModuleEvaluation g.1).obj M :=
  Classical.choose ((A.positiveActionSpan M g.1).mkQ_surjective
    (Module.Free.chooseBasis k (A.RightModuleTopSpace M g.1) g.2))

@[simp] theorem rightTopBasisLift_mkQ (M : A.RightModule) (g : A.rightTopBasisIndex M) :
    (A.positiveActionSpan M g.1).mkQ (A.rightTopBasisLift M g) =
      Module.Free.chooseBasis k (A.RightModuleTopSpace M g.1) g.2 :=
  Classical.choose_spec ((A.positiveActionSpan M g.1).mkQ_surjective
    (Module.Free.chooseBasis k (A.RightModuleTopSpace M g.1) g.2))

noncomputable def rightTopBasisFreeModule (M : A.RightModule) : A.RightModule :=
  ∐ fun g : A.rightTopBasisIndex M => A.representable g.1

noncomputable def rightTopBasisFreeModuleπ (M : A.RightModule) : A.rightTopBasisFreeModule M ⟶ M :=
  Sigma.desc fun g => (A.representableYonedaEquiv g.1 M).symm (A.rightTopBasisLift M g)

instance rightTopBasisFreeModule_projective (M : A.RightModule) :
    Projective (A.rightTopBasisFreeModule M) := by
  dsimp [rightTopBasisFreeModule]
  infer_instance

theorem rightTopBasisFreeModuleπ_generator (M : A.RightModule) (g : A.rightTopBasisIndex M) :
    (A.rightModuleEvaluation g.1).map (A.rightTopBasisFreeModuleπ M)
      ((A.rightModuleEvaluation g.1).map
        (Sigma.ι (fun g : A.rightTopBasisIndex M => A.representable g.1) g) (A.id g.1)) =
      A.rightTopBasisLift M g := by
  have h := Sigma.ι_desc (fun g : A.rightTopBasisIndex M =>
    (A.representableYonedaEquiv g.1 M).symm (A.rightTopBasisLift M g)) g
  have h' := congrArg (A.representableYonedaEquiv g.1 M) h
  rw [A.representableYonedaEquiv_comp, LinearEquiv.apply_symm_apply] at h'
  exact h'

theorem rightTopBasisFreeModuleπ_top_surjective (M : A.RightModule) (i : ℤ) :
    Function.Surjective (((A.positiveActionSpan M i).mkQ).comp
      ((A.rightModuleEvaluation i).map (A.rightTopBasisFreeModuleπ M)).hom) := by
  apply LinearMap.range_eq_top.mp
  apply top_unique
  rw [← (Module.Free.chooseBasis k (A.RightModuleTopSpace M i)).span_eq]
  apply Submodule.span_le.mpr
  rintro x ⟨j, rfl⟩
  let g : A.rightTopBasisIndex M := ⟨i,j⟩
  refine ⟨(A.rightModuleEvaluation i).map
    (Sigma.ι (fun g : A.rightTopBasisIndex M => A.representable g.1) g) (A.id i), ?_⟩
  change (A.positiveActionSpan M i).mkQ
    ((A.rightModuleEvaluation i).map (A.rightTopBasisFreeModuleπ M)
      ((A.rightModuleEvaluation i).map
        (Sigma.ι (fun g : A.rightTopBasisIndex M => A.representable g.1) g) (A.id i))) = _
  rw [A.rightTopBasisFreeModuleπ_generator M g, A.rightTopBasisLift_mkQ M g]

theorem rightTopBasisFreeModuleπ_range_add_radical (M : A.RightModule) (i : ℤ) :
    LinearMap.range ((A.rightModuleEvaluation i).map (A.rightTopBasisFreeModuleπ M)).hom ⊔
      A.positiveActionSpan M i = ⊤ := by
  apply (Submodule.eq_top_iff').mpr
  intro x
  obtain ⟨y, hy⟩ := A.rightTopBasisFreeModuleπ_top_surjective M i
    ((A.positiveActionSpan M i).mkQ x)
  let f := ((A.rightModuleEvaluation i).map (A.rightTopBasisFreeModuleπ M)).hom
  refine Submodule.mem_sup.mpr ⟨f y, ⟨y,rfl⟩, x-f y, ?_, by simp⟩
  apply (Submodule.Quotient.mk_eq_zero _).mp
  change (A.positiveActionSpan M i).mkQ (x-f y) = 0
  rw [map_sub]
  change (A.positiveActionSpan M i).mkQ x -
    (((A.positiveActionSpan M i).mkQ).comp f) y = 0
  rw [hy, sub_self]

theorem rightTopBasisFreeModuleπ_epi (M : A.RightModule) (b : ℤ)
    (hb : ∀ i : ℤ, b < i → IsZero ((A.rightModuleEvaluation i).obj M)) :
    Epi (A.rightTopBasisFreeModuleπ M) :=
  A.rightModule_epi_of_boundedAbove_range_add_radical _ b hb
    (A.rightTopBasisFreeModuleπ_range_add_radical M)

end ASGinzburg.ZAlgebra
