import ASGinzburg.UnrolledJacobianRelations
import ASGinzburg.UnrolledComponentHeights
import ASGinzburg.GeneratedLinearIdeals
import ASGinzburg.ASPresentationQuotient

/-! The actual unrolled Jacobian algebra is the quotient by the ideal
generated by all sheet translates of genuine path-valued cyclic derivatives. -/
namespace ASGinzburg.CutQuiver
open ZAlgebra
universe u
variable (Q : CutQuiver) (k : Type u) [Field k]

noncomputable def integerJacobianRelation (a : Q.Arrow) (φ : Q.Potential k) (m : ℤ) :
    (Q.unrolledPathZAlgebra k).Hom (Q.height (Q.target a,m))
      (Q.height (Q.source a,m+((1-Q.cutDegree a:ℕ):ℤ))) :=
  Q.unrolledComponentHeightEquiv k _ _ (Q.unrolledJacobianRelation k a φ m)

theorem integerJacobianRelation_mem_square (a : Q.Arrow) (φ : Q.Potential k) (m : ℤ) :
    Q.integerJacobianRelation k a φ m ∈
      ((Q.unrolledArrowIdeal k).mul (Q.unrolledArrowIdeal k)).hom
        (Q.height (Q.target a,m)) (Q.height (Q.source a,m+((1-Q.cutDegree a:ℕ):ℤ))) := by
  rw [Q.unrolledArrowIdeal_square k]
  exact Q.unrolledComponentHeightEquiv_mem_filtration k 2
    (Q.unrolledJacobianRelation_supported_long k a φ m)

noncomputable def jacobianGenerators (φ : Q.Potential k) (i j : ℤ) :
    Set ((Q.unrolledPathZAlgebra k).Hom i j) :=
  {f | ∃ a m,
    ∃ hi : Q.height (Q.target a,m)=i,
    ∃ hj : Q.height (Q.source a,m+((1-Q.cutDegree a:ℕ):ℤ))=j,
      (Q.unrolledPathZAlgebra k).homTransport _ _ i j hi hj
        (Q.integerJacobianRelation k a φ m)=f}

theorem jacobianGenerators_subset_square (φ : Q.Potential k) (i j : ℤ) :
    Q.jacobianGenerators k φ i j ⊆
      ((Q.unrolledArrowIdeal k).mul (Q.unrolledArrowIdeal k)).hom i j := by
  rintro f ⟨a,m,hi,hj,rfl⟩
  subst i j
  exact Q.integerJacobianRelation_mem_square k a φ m

noncomputable def unrolledJacobianIdeal (φ : Q.Potential k) :
    (Q.unrolledPathZAlgebra k).LinearIdeal :=
  LinearIdeal.generated (Q.jacobianGenerators k φ)

theorem unrolledJacobianIdeal_le_square (φ : Q.Potential k) (i j : ℤ) :
    (Q.unrolledJacobianIdeal k φ).hom i j ≤
      ((Q.unrolledArrowIdeal k).mul (Q.unrolledArrowIdeal k)).hom i j :=
  LinearIdeal.generated_le _ _ (Q.jacobianGenerators_subset_square k φ) i j

theorem unrolledJacobianIdeal_diagonal_eq_bot (φ : Q.Potential k) (i : ℤ) :
    (Q.unrolledJacobianIdeal k φ).hom i i=⊥ :=
  Q.ideal_diagonal_eq_bot_of_le_arrow_square k _ (Q.unrolledJacobianIdeal_le_square k φ) i

noncomputable def unrolledJacobianZAlgebra (φ : Q.Potential k) : ZAlgebra.{u,u} k :=
  (Q.unrolledJacobianIdeal k φ).quotient (Q.unrolledJacobianIdeal_diagonal_eq_bot k φ)

noncomputable def unrolledJacobianQuotientMap (φ : Q.Potential k) :
    Homomorphism (Q.unrolledPathZAlgebra k) (Q.unrolledJacobianZAlgebra k φ) :=
  (Q.unrolledJacobianIdeal k φ).quotientMap (Q.unrolledJacobianIdeal_diagonal_eq_bot k φ)

theorem unrolledJacobianQuotientMap_surjective (φ : Q.Potential k) (i j : ℤ) :
    Function.Surjective ((Q.unrolledJacobianQuotientMap k φ).map i j) :=
  (Q.unrolledJacobianIdeal k φ).quotientMap_surjective _ i j

theorem unrolledJacobianQuotientMap_kernel (φ : Q.Potential k) (i j : ℤ) :
    (Q.unrolledJacobianQuotientMap k φ).kernel.hom i j=
      (Q.unrolledJacobianIdeal k φ).hom i j :=
  (Q.unrolledJacobianIdeal k φ).quotientMap_kernel _ i j

theorem unrolledJacobianQuotientMap_relation_zero (a : Q.Arrow) (φ : Q.Potential k) (m : ℤ) :
    (Q.unrolledJacobianQuotientMap k φ).map
      (Q.height (Q.target a,m)) (Q.height (Q.source a,m+((1-Q.cutDegree a:ℕ):ℤ)))
        (Q.integerJacobianRelation k a φ m)=0 := by
  apply (Submodule.Quotient.mk_eq_zero _).mpr
  apply LinearIdeal.subset_generated
  exact ⟨a,m,rfl,rfl,rfl⟩

end ASGinzburg.CutQuiver
