import ASGinzburg.UnrolledJacobianAlgebra

/-! The genuine ideal generated by the cut-arrow derivatives on
all sheets, with its unconditional inclusion in the full Jacobian ideal. -/
namespace ASGinzburg.CutQuiver
open ZAlgebra
universe u
variable (Q : CutQuiver) (k : Type u) [Field k]

noncomputable def cutJacobianGenerators (φ : Q.Potential k) (i j : ℤ) :
    Set ((Q.unrolledPathZAlgebra k).Hom i j) :=
  {f | ∃ a m, Q.cut a=true ∧ ∃ hi : Q.height (Q.target a,m)=i,
    ∃ hj : Q.height (Q.source a,m+((1-Q.cutDegree a:ℕ):ℤ))=j,
      (Q.unrolledPathZAlgebra k).homTransport _ _ i j hi hj
        (Q.integerJacobianRelation k a φ m)=f}

theorem cutJacobianGenerators_subset (φ : Q.Potential k) (i j : ℤ) :
    Q.cutJacobianGenerators k φ i j ⊆ Q.jacobianGenerators k φ i j := by
  rintro f ⟨a,m,_,hi,hj,h⟩
  exact ⟨a,m,hi,hj,h⟩

noncomputable def unrolledCutJacobianIdeal (φ : Q.Potential k) :
    (Q.unrolledPathZAlgebra k).LinearIdeal :=
  LinearIdeal.generated (Q.cutJacobianGenerators k φ)

theorem unrolledCutJacobianIdeal_le_Jacobian (φ : Q.Potential k) (i j : ℤ) :
    (Q.unrolledCutJacobianIdeal k φ).hom i j ≤ (Q.unrolledJacobianIdeal k φ).hom i j := by
  apply LinearIdeal.generated_le
  intro i j f hf
  exact LinearIdeal.subset_generated _ _ _ (Q.cutJacobianGenerators_subset k φ i j hf)

end ASGinzburg.CutQuiver
