import work.ASGinzburgDraft.PeriodCutEnvelopingBigrading
import work.ASGinzburgDraft.PeriodCutEnvelopingScalars
import work.ASGinzburgDraft.AlgebraEnvelopingRegularFinite

/-! The actual multiplication bimodule respects the genuine unsigned
enveloping degrees. Its underlying graded ring is generated by one as
an ordinary enveloping module, independently of vector-space dimension. -/
namespace ASGinzburg.ZAlgebra.PeriodIso
open scoped TensorProduct
universe u v w
variable {k : Type u} [Field k] {A : ZAlgebra.{u,v} k} {p : ℤ}
variable (E : A.PeriodIso p) {ι : Type w} [Fintype ι] (vertex : ι → ℤ)

noncomputable def cutEnvelopingRegularModule :
    Module (AlgebraEnvelopingRing k (E.CutGradedRing vertex)) (E.CutGradedRing vertex) :=
  regularEnvelopingModule k (E.CutGradedRing vertex)

theorem cutEnvelopingRegularModule_homogeneous_smul (i j n : ℕ)
    (x : E.CutGradedBlock vertex i) (y : E.CutGradedBlock vertex j)
    (z : E.CutGradedBlock vertex n) :
    letI := E.cutEnvelopingRegularModule vertex
    E.cutEnvelopingHomogeneousInclusion vertex (i,j) (x ⊗ₜ[k] y) •
      E.cutHomogeneousInclusion vertex n z =
    E.cutHomogeneousInclusion vertex ((i+n)+j)
      (E.cutBlockMul vertex (i+n) j (E.cutBlockMul vertex i n x z) y) := by
  letI := E.cutEnvelopingRegularModule vertex
  rw [cutEnvelopingHomogeneousInclusion_tmul, regularEnvelopingModule_tmul_smul,
    cutHomogeneousInclusion_mul, cutHomogeneousInclusion_mul]

theorem cutEnvelopingRegularModule_finite :
    letI := E.cutEnvelopingRegularModule vertex
    Module.Finite (AlgebraEnvelopingRing k (E.CutGradedRing vertex)) (E.CutGradedRing vertex) :=
  regularEnvelopingModule_finite_of_cyclic k (E.CutGradedRing vertex)

end ASGinzburg.ZAlgebra.PeriodIso
