import work.ASGinzburgDraft.ASCutGradedResolutionFiniteness
import work.ASGinzburgDraft.ASCutGradedResolutionMinimality
import work.ASGinzburgDraft.ASResolutionComplexMinimality
import work.ASGinzburgDraft.FiniteModuleCatCoproduct
import work.ASGinzburgDraft.PeriodCutFiniteProjectives
import work.ASGinzburgDraft.PeriodCutForgetGrading
import work.ASGinzburgDraft.PeriodCutGradedMinimality
import work.ASGinzburgDraft.PeriodCutGradedModuleRadical
import work.ASGinzburgDraft.PeriodCutGradedRepresentableGenerators
import work.ASGinzburgDraft.PeriodCutIntegerHomogeneousSpaces
import work.ASGinzburgDraft.PeriodCutPositiveActionRadical
import work.ASGinzburgDraft.PeriodCutRadicalCornerEntries
import work.ASGinzburgDraft.PeriodCutRepresentableActionMap
import work.ASGinzburgDraft.PeriodCutRepresentableRightIdeal
import work.ASGinzburgDraft.PeriodCutRepresentableRightIdealGrading
import work.ASGinzburgDraft.PeriodCutRepresentableValueProjection
import work.ASGinzburgDraft.PeriodCutRepresentableValues
import work.ASGinzburgDraft.PeriodCutRightVertexSpaces

#print axioms ASGinzburg.ZAlgebra.ASRegular.cutGradedSimpleProjectiveResolution_finite
#print axioms ASGinzburg.ZAlgebra.ASRegular.cutGradedSimpleProjectiveResolution_minimal
#print axioms ASGinzburg.ZAlgebra.ASResolution.complex_d_succ_minimal
#print axioms ASGinzburg.finiteModuleCatCoproduct
#print axioms ASGinzburg.ZAlgebra.PeriodIso.cornerRepresentable_ring_finite
#print axioms ASGinzburg.ZAlgebra.PeriodIso.cornerFiniteRepresentableSum_ring_finite
#print axioms ASGinzburg.ZAlgebra.PeriodIso.cornerFiniteProjective_ring_finite
#print axioms ASGinzburg.ZAlgebra.PeriodIso.cutGradedForgetFunctor
#print axioms ASGinzburg.ZAlgebra.PeriodIso.cutGradedForgetFunctorAdditive
#print axioms ASGinzburg.ZAlgebra.PeriodIso.cornerModuleRingFunctor
#print axioms ASGinzburg.ZAlgebra.PeriodIso.cornerModuleRingFunctorAdditive
#print axioms ASGinzburg.ZAlgebra.PeriodIso.CutGradedRightModule.IsMinimalMorphism
#print axioms ASGinzburg.ZAlgebra.PeriodIso.cornerGradedModuleMap_minimal
#print axioms ASGinzburg.ZAlgebra.PeriodIso.CutGradedRightModule.gradedRadicalActionSpan
#print axioms ASGinzburg.ZAlgebra.PeriodIso.CutGradedRightModule.gradedRadicalAction_mem
#print axioms ASGinzburg.ZAlgebra.PeriodIso.CutGradedRightModule.gradedRadicalActionSpan_action_mem
#print axioms ASGinzburg.ZAlgebra.PeriodIso.CutGradedRightModule.gradedRadicalActionSpan_map_mem
#print axioms ASGinzburg.ZAlgebra.PeriodIso.cornerRepresentableGenerator
#print axioms ASGinzburg.ZAlgebra.PeriodIso.cornerRepresentableGenerator_corner_action
#print axioms ASGinzburg.ZAlgebra.PeriodIso.cornerRepresentableGenerator_mem_grade
#print axioms ASGinzburg.ZAlgebra.PeriodIso.cornerRepresentableGenerator_span_top
#print axioms ASGinzburg.ZAlgebra.PeriodIso.cornerGradedRepresentable_finite
#print axioms ASGinzburg.ZAlgebra.PeriodIso.cutIntegerHomogeneousSpace
#print axioms ASGinzburg.ZAlgebra.PeriodIso.cutIntegerHomogeneousSpace_ofNat
#print axioms ASGinzburg.ZAlgebra.PeriodIso.cutIntegerHomogeneousSpace_negative
#print axioms ASGinzburg.ZAlgebra.PeriodIso.integerCorner_le_integerHomogeneousSpace
#print axioms ASGinzburg.ZAlgebra.PeriodIso.cornerModule_positive_action_mem_radical
#print axioms ASGinzburg.ZAlgebra.PeriodIso.cornerPositiveActionSpan_lof_mem_radical
#print axioms ASGinzburg.ZAlgebra.PeriodIso.cutHomogeneousComponent_mem_gradedJacobson
#print axioms ASGinzburg.ZAlgebra.PeriodIso.cornerCoverHom_mem_gradedJacobson
#print axioms ASGinzburg.ZAlgebra.PeriodIso.cornerRepresentableActionMap
#print axioms ASGinzburg.ZAlgebra.PeriodIso.cornerRepresentableActionMap_valueMap
#print axioms ASGinzburg.ZAlgebra.PeriodIso.cornerRepresentableValueMap_injective
#print axioms ASGinzburg.ZAlgebra.PeriodIso.cornerRepresentableValueMap_generator
#print axioms ASGinzburg.ZAlgebra.PeriodIso.cornerRepresentableRightIdealEquiv
#print axioms ASGinzburg.ZAlgebra.PeriodIso.cornerRepresentableActionMap_mul
#print axioms ASGinzburg.ZAlgebra.PeriodIso.cornerRepresentableValueMap_right_action
#print axioms ASGinzburg.ZAlgebra.PeriodIso.cornerRepresentableValueMap_degreeInsertion_mem
#print axioms ASGinzburg.ZAlgebra.PeriodIso.cornerRepresentableValueMap_mem_grade
#print axioms ASGinzburg.ZAlgebra.PeriodIso.cornerRepresentableActionMap_mem_grade
#print axioms ASGinzburg.ZAlgebra.PeriodIso.cornerRepresentableValueMap_actionMap_homogeneous
#print axioms ASGinzburg.ZAlgebra.PeriodIso.cornerRepresentableValueMap_actionMap
#print axioms ASGinzburg.ZAlgebra.PeriodIso.cornerRepresentableValueMap
#print axioms ASGinzburg.ZAlgebra.PeriodIso.cornerRepresentableValueMap_lof
#print axioms ASGinzburg.ZAlgebra.PeriodIso.cornerRepresentableValueMap_corner_action
#print axioms ASGinzburg.ZAlgebra.PeriodIso.cornerRepresentableValueMap_target_absorption
#print axioms ASGinzburg.ZAlgebra.PeriodIso.cutRightVertexSpace
#print axioms ASGinzburg.ZAlgebra.PeriodIso.cutRightVertexSpace_mul_mem
